import { getCurrent } from "@/features/auth/queries";
import { Metadata } from "next";
import { redirect } from "next/navigation";

interface WorkspaceIdJoinPageProps {
  params: {
    inviteCode: string;
  };
}

export const metadata: Metadata = {
  title: "Joining",
  description: "Generated by create next app",
};

const WorkspaceIdJoinPage = async () => {
  const user = await getCurrent();
  if (!user) redirect("/sign-in");
  return <div>Workspace Id Join Page</div>;
};

export default WorkspaceIdJoinPage;
